# Generated by Django 2.2.19 on 2021-03-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=50)),
                ('mail_id', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Custpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_w', models.IntegerField(max_length=3)),
                ('size_h', models.IntegerField(max_length=3)),
                ('quantity', models.IntegerField(max_length=5)),
                ('requirements', models.CharField(max_length=500)),
                ('painting_type', models.CharField(choices=[('Tanjore', 'Tanjore'), ('Acrylic', 'Acrylic'), ('Oil', 'Oil'), ('Pencil sketch', 'Pencil sketch')], default=None, max_length=20)),
                ('type_type', models.CharField(choices=[('Flat work', 'Flat work'), ('2D', '2 Dimension'), ('3D', '3 Dimension')], default=None, max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artgallery.Customer')),
            ],
        ),
    ]
