# Generated by Django 2.2.19 on 2021-03-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='custpro',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='custpro',
            name='size_h',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='custpro',
            name='size_w',
            field=models.IntegerField(),
        ),
    ]
