# Generated by Django 3.1.7 on 2021-03-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0002_auto_20210314_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('date', models.DateField()),
                ('p_cusname', models.CharField(max_length=20)),
                ('p_cusmail', models.CharField(max_length=20)),
                ('p_code', models.CharField(max_length=10)),
                ('p_name', models.CharField(max_length=25)),
                ('p_painting_type', models.CharField(choices=[('Tanjore', 'Tanjore'), ('Acrylic', 'Acrylic'), ('Oil', 'Oil'), ('Pencil sketch', 'Pencil sketch')], default=None, max_length=20)),
                ('p_type_type', models.CharField(choices=[('Flat work', 'Flat work'), ('2D', '2 Dimension'), ('3D', '3 Dimension')], default=None, max_length=20)),
                ('psize_w', models.IntegerField()),
                ('psize_h', models.IntegerField()),
                ('p_price', models.IntegerField()),
                ('p_quantity', models.IntegerField()),
                ('p_totalprice', models.IntegerField()),
                ('p_dispatchedstatus', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artgallery.customer')),
            ],
        ),
    ]
