# Generated by Django 3.1.7 on 2021-03-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0003_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='p_cusmail',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='p_cusname',
        ),
    ]
