# Generated by Django 3.1.7 on 2021-03-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0004_auto_20210321_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.IntegerField()),
                ('s_date', models.DateField()),
                ('sp_name', models.CharField(max_length=25)),
                ('sd_name', models.CharField(max_length=25)),
                ('sp_type', models.CharField(max_length=25)),
                ('s_size_w', models.CharField(max_length=7)),
                ('s_size_h', models.CharField(max_length=7)),
                ('s_price', models.IntegerField()),
                ('s_quantity', models.CharField(max_length=7)),
                ('s_totalprice', models.IntegerField()),
            ],
        ),
    ]
