# Generated by Django 3.1.7 on 2021-03-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0005_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
