# Generated by Django 3.1.7 on 2021-04-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0007_auto_20210403_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_date', models.DateField()),
                ('t_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='s_quantity',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_id',
            field=models.CharField(max_length=12),
        ),
    ]
